[aws]
disabled = true

[directory]
truncate_to_repo = false

[gcloud]
disabled = true

[package]
format = "[$symbol$version]($style) "

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
cherry_pick = "[ğŸ’ PICKING](bold red)"
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
conflicted = "ğŸ³"
deleted = "ğŸ—‘"
diverged = "ğŸŒ¿"
modified = "ğŸ“"
renamed = "ğŸ‘…"
staged = '[ ++\($count\)](green)'
stashed = "ğŸ“¦"
untracked = "ğŸ¤·â€"

[battery]
full_symbol = "ğŸ”‹"

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
style = "bold red"
threshold = 10

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
discharging_symbol = "ğŸ’€"
style = "bold yellow"
threshold = 20

[php]
format = "via [$symbol$version]($style) "
style = "147 bold"
symbol = "ğŸ˜"

[bun]
symbol = "ğŸ° "

[nodejs]
format = ""
